# Generated by Django 6.0 on 2026-03-26 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surf_school', '0002_solicitudcancelacion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reserva',
            name='unique_reserva_alumno_clase',
        ),
    ]
