# Generated by Django 6.0 on 2026-03-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surf_school', '0003_remove_reserva_unique_reserva_alumno_clase'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
